In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape((3,3))
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [6]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
ser1 =  Series([0,1,2],index=['T','U','V'])

ser2 = Series([3,4],index=['X','Y'])

In [8]:
ser1

T    0
U    1
V    2
dtype: int64

In [9]:
ser2

X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1,ser2],axis=1)

0   1
T   0 NaN
U   1 NaN
V   2 NaN
X NaN   3
Y NaN   4

In [12]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [13]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X', 'Y', 'Z'])
dframe2 = DataFrame(np.random.randn(3, 3), columns=['Y', 'Q', 'X'])

In [14]:
dframe1

X         Y         Z
0  0.905625  0.668848  0.187654
1  0.536348 -0.213099  1.303537
2  2.085553  0.709585  0.483501
3 -0.736683  1.357729 -0.425127

In [15]:
dframe2

Y         Q         X
0  0.480853 -0.708534 -0.056192
1  0.743445 -0.369329  0.810439
2 -0.684676  0.210907 -0.473291

In [16]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN  0.905625  0.668848  0.187654
1       NaN  0.536348 -0.213099  1.303537
2       NaN  2.085553  0.709585  0.483501
3       NaN -0.736683  1.357729 -0.425127
0 -0.708534 -0.056192  0.480853       NaN
1 -0.369329  0.810439  0.743445       NaN
2  0.210907 -0.473291 -0.684676       NaN

In [17]:
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN  0.905625  0.668848  0.187654
1       NaN  0.536348 -0.213099  1.303537
2       NaN  2.085553  0.709585  0.483501
3       NaN -0.736683  1.357729 -0.425127
4 -0.708534 -0.056192  0.480853       NaN
5 -0.369329  0.810439  0.743445       NaN
6  0.210907 -0.473291 -0.684676       NaN

In [ ]:
#For more info in documentation:
url='http://pandas.pydata.org/pandas-docs/stable/generated/pandas.concat.html'