In [1]:
import numpy as np

In [2]:
my_list1 = [1,2,3,4]

In [3]:
my_array1 = np.array(my_list1)

In [4]:
my_array1

array([1, 2, 3, 4])

In [25]:
my_list2 = [11,22,33,44]

In [26]:
my_lists = [my_list1, my_list2]

In [27]:
my_array2 = np.array(my_lists)

In [24]:
my_array2 #what happens if they are not the same length?

array([[1, 2, 3, 4], [11, 22, 33]], dtype=object)

In [10]:
my_array2.shape

(2, 4)

In [11]:
my_array2.dtype

dtype('int32')

In [13]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [14]:
my_zeros_array = np.zeros(5)

In [15]:
my_zeros_array.dtype

dtype('float64')

In [16]:
np.ones([5,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [17]:
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [18]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])